name: wakelock_windows
description: >-2
  Windows platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 0.2.1
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock_windows

environment:
  sdk: ^2.18.6
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  win32: ^5.0.9
  file_picker: ^5.5.0
  device_info_plus: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

  wakelock_platform_interface:
    path: ../wakelock_platform_interface

# todo: use dartPluginClass declaration once that lands on stable (https://github.com/flutter/flutter/issues/52267_
#flutter:
#  plugin:
#    platforms:
#      windows:
#        dartPluginClass: WakelockWindows
