name: wakelock
description: >-2
  Plugin that allows you to keep the device screen awake, i.e. prevent the screen from sleeping on
  Android, iOS, macOS, Windows, and web.
version: 0.6.2
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock

environment:
  sdk: ^2.18.6

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.9.1
  device_info_plus: ^9.0.3
  wakelock_macos:
    git:
      url: https://github.com/krispcall/wakelock.git
      ref: main
      path: wakelock_macos

  wakelock_platform_interface:
    git:
      url: https://github.com/krispcall/wakelock.git
      ref: main
      path: wakelock_platform_interface

  wakelock_web:
    git:
      url: https://github.com/krispcall/wakelock.git
      ref: main
      path: wakelock_web

  wakelock_windows:
    git:
      url: https://github.com/krispcall/wakelock.git
      ref: main
      path: wakelock_windows

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.4
  pigeon: ^12.0.0 # flutter pub run pigeon --input "pigeons/messages.dart"

flutter:
  plugin:
    platforms:
      android:
        package: creativemaybeno.wakelock
        pluginClass: WakelockPlugin
      ios:
        pluginClass: WakelockPlugin
      macos:
        default_package: wakelock_macos
      windows:
        default_package: wakelock_windows
      web:
        default_package: wakelock_web
